# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testWid.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(649, 540)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.horizontalScrollBar_2 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_2.setMinimumSize(QtCore.QSize(250, 0))
        self.horizontalScrollBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_2.setObjectName("horizontalScrollBar_2")
        self.gridLayout.addWidget(self.horizontalScrollBar_2, 1, 2, 1, 1)
        self.horizontalScrollBar_4 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_4.setObjectName("horizontalScrollBar_4")
        self.gridLayout.addWidget(self.horizontalScrollBar_4, 0, 2, 1, 1)
        self.horizontalScrollBar = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.gridLayout.addWidget(self.horizontalScrollBar, 0, 1, 1, 1)
        self.horizontalScrollBar_6 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_6.setObjectName("horizontalScrollBar_6")
        self.gridLayout.addWidget(self.horizontalScrollBar_6, 2, 2, 1, 1)
        self.horizontalScrollBar_5 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_5.setObjectName("horizontalScrollBar_5")
        self.gridLayout.addWidget(self.horizontalScrollBar_5, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 3, 1, 1)
        self.horizontalScrollBar_3 = QtWidgets.QScrollBar(Form)
        self.horizontalScrollBar_3.setMinimumSize(QtCore.QSize(250, 0))
        self.horizontalScrollBar_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar_3.setObjectName("horizontalScrollBar_3")
        self.gridLayout.addWidget(self.horizontalScrollBar_3, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_3.addWidget(self.checkBox, 0, 4, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 2, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_3.addWidget(self.spinBox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(918, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_3, 4, 0, 1, 1)
        self.runButton = QtWidgets.QPushButton(Form)
        self.runButton.setObjectName("runButton")
        self.gridLayout_2.addWidget(self.runButton, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftView = QtWidgets.QGraphicsView(Form)
        self.leftView.setObjectName("leftView")
        self.horizontalLayout.addWidget(self.leftView)
        self.rightView = QtWidgets.QGraphicsView(Form)
        self.rightView.setObjectName("rightView")
        self.horizontalLayout.addWidget(self.rightView)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.label_7.raise_()
        self.runButton.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Min V"))
        self.label_2.setText(_translate("Form", "Min S"))
        self.label.setText(_translate("Form", "Min H"))
        self.label_6.setText(_translate("Form", "Max S"))
        self.label_4.setText(_translate("Form", "Max H"))
        self.label_5.setText(_translate("Form", "Max V"))
        self.checkBox.setText(_translate("Form", "Mask"))
        self.label_7.setText(_translate("Form", "ColorNumber"))
        self.runButton.setText(_translate("Form", "Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

